### ISSUE TITLE
purple_init_mute_plugin

### ISSUE THREAD

**Issue by optikfluffel** [rampion/example-libpurple-plugin-for-adium#1]
Hey :)

I don't quite understand the part where you call `purple_init_mute_plugin();` in `MuteWrapper.m`. I can't get your example up and running and I think it's because `purple_init_mute_plugin` doesn't exist anywhere. Hope you can help me out to better understand that thing. Thanks

**Comment by rampion** [comment]
Thanks for pinging me!

Some of this may be explained by [the blog entry I wrote explaining this](http://rampion.blogspot.com/2008/09/howto-wrap-libpurple-plugin-for-adium.html), which I completely don't mention in any README or anything. Sorry, my bad.

Anyway, back when I wrote this in 2008, I was working with Adium 1.2.5 and pidgin 2.4.2.

At the time, the function `purple_init_mute_plugin()` was defined in mute.c by the `PURPLE_INIT_PLUGIN(mute, init_plugin, info)` call at the end when `PURPLE_STATIC_PRPL` is defined at compile time. 

It [looks like that's still the way to do it](https://github.com/adium/adium/search?q=PURPLE_INIT_PLUGIN&ref=cmdform), as you [can see in the Adium source yourself](https://github.com/adium/adium/blob/116c2c15b6d220dd257901845f041edc397a011a/Frameworks/libpurple.framework/Versions/2.10.7r5340f4a9bd6a/Headers/plugin.h#L221).

I suspect you're not seeing `purple_init_mute_plugin` because `PURPLE_PLUGINS` is defined but `PURPLE_STATIC_PRPL` isn't.

So in that case, it looks like you need to call `purple_init_plugin` instead.
